---
- name: Setup MongoDB
  hosts: all
  become: true
  tasks:
    - name: Add apt key
      apt_key:
        id: EA312927
        keyserver: keyserver.ubuntu.com

    - name: Add apt repository for mongodb
      apt_repository:
        repo: deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
        state: present

    - name: Install mongoDB package
      apt:
        name: mongodb-org
        state: present
        update_cache: yes

    - name: Enabled service mongod
      systemd:
        name: mongod
        enabled: yes
